import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      appName: "DermScan AI",
      tagline: "AI-powered skin health for India",
      startScan: "Start New Scan",
      viewHistory: "Scan History",
      step1Title: "Capture Photo",
      step1Desc: "Take a clear photo of the affected area",
      step2Title: "Symptom Quiz",
      step2Desc: "Answer 5 quick questions",
      step3Title: "AI Assessment",
      step3Desc: "Get preliminary results",
      captureButton: "Capture Photo",
      retakeButton: "Retake",
      confirmPhoto: "Confirm & Continue",
      quizBodyArea: "Where is it located?",
      quizDuration: "How long has it been there?",
      quizItchBurn: "Does it itch or burn?",
      quizSpreading: "Is it spreading?",
      quizAllergies: "Any known allergies?",
      quizSkinTone: "Select your skin tone",
      yes: "Yes",
      no: "No",
      days: "Days",
      weeks: "Weeks",
      months: "Months",
      analyzing: "Analyzing with AI...",
      resultsTitle: "Preliminary Assessment",
      triageNow: "Seek Care NOW",
      triageWeek: "See Doctor within a Week",
      triageHome: "Monitor at Home",
      findDoctor: "Find Nearest Doctor",
      shareWhatsApp: "Share on WhatsApp",
      disclaimer: "Disclaimer: This is an AI-powered support tool, not a medical diagnosis. Always consult a qualified doctor.",
      cameraGuide: "Keep the area inside the circle. Ensure good lighting.",
      lowLight: "Low light detected. Please move to a brighter area.",
      blurDetected: "Image might be blurry. Please hold steady.",
      processing: "Compressing for 2G...",
      historyEmpty: "No scans yet. Start your first scan!",
      deleteScan: "Delete Scan",
      backToHome: "Back to Home",
      voiceInput: "Tap to speak (Hindi)",
    }
  },
  hi: {
    translation: {
      appName: "DermScan AI",
      tagline: "भारत के लिए AI-आधारित त्वचा स्वास्थ्य",
      startScan: "नया स्कैन शुरू करें",
      viewHistory: "स्कैन इतिहास",
      step1Title: "फोटो लें",
      step1Desc: "प्रभावित क्षेत्र की स्पष्ट फोटो लें",
      step2Title: "लक्षण प्रश्नोत्तरी",
      step2Desc: "5 त्वरित प्रश्नों के उत्तर दें",
      step3Title: "AI मूल्यांकन",
      step3Desc: "प्रारंभिक परिणाम प्राप्त करें",
      captureButton: "फोटो खींचें",
      retakeButton: "फिर से लें",
      confirmPhoto: "पुष्टि करें और आगे बढ़ें",
      quizBodyArea: "यह कहाँ स्थित है?",
      quizDuration: "यह कितने समय से है?",
      quizItchBurn: "क्या इसमें खुजली या जलन होती है?",
      quizSpreading: "क्या यह फैल रहा है?",
      quizAllergies: "कोई ज्ञात एलर्जी?",
      quizSkinTone: "अपनी त्वचा का रंग चुनें",
      yes: "हाँ",
      no: "नहीं",
      days: "दिन",
      weeks: "सप्ताह",
      months: "महीने",
      analyzing: "AI के साथ विश्लेषण हो रहा है...",
      resultsTitle: "प्रारंभिक मूल्यांकन",
      triageNow: "अभी डॉक्टर से मिलें",
      triageWeek: "एक सप्ताह के भीतर डॉक्टर को दिखाएं",
      triageHome: "घर पर निगरानी रखें",
      findDoctor: "नजदीकी डॉक्टर खोजें",
      shareWhatsApp: "WhatsApp पर साझा करें",
      disclaimer: "अस्वीकरण: यह एक AI-आधारित सहायता उपकरण है, चिकित्सा निदान नहीं। हमेशा योग्य डॉक्टर से परामर्श लें।",
      cameraGuide: "क्षेत्र को घेरे के अंदर रखें। अच्छी रोशनी सुनिश्चित करें।",
      lowLight: "कम रोशनी मिली। कृपया उजाले वाली जगह पर जाएं।",
      blurDetected: "फोटो धुंधली हो सकती है। कृपया स्थिर रहें।",
      processing: "2G के लिए कंप्रेस हो रहा है...",
      historyEmpty: "अभी तक कोई स्कैन नहीं। अपना पहला स्कैन शुरू करें!",
      deleteScan: "स्कैन हटाएं",
      backToHome: "होम पर वापस जाएं",
      voiceInput: "बोलने के लिए टैप करें (हिंदी)",
    }
  },
  ta: {
    translation: {
      appName: "DermScan AI",
      tagline: "இந்தியாவிற்கான AI-இயங்கும் தோல் ஆரோக்கியம்",
      startScan: "புதிய ஸ்கேன் தொடங்கவும்",
      viewHistory: "ஸ்கேன் வரலாறு",
      step1Title: "புகைப்படம் எடுக்கவும்",
      step1Desc: "பாதிக்கப்பட்ட பகுதியின் தெளிவான புகைப்படத்தை எடுக்கவும்",
      step2Title: "அறிகுறி வினாடி வினா",
      step2Desc: "5 விரைவான கேள்விகளுக்கு பதிலளிக்கவும்",
      step3Title: "AI மதிப்பீடு",
      step3Desc: "ஆரம்ப முடிவுகளைப் பெறுங்கள்",
      captureButton: "புகைப்படம் எடு",
      retakeButton: "மீண்டும் எடு",
      confirmPhoto: "உறுதிப்படுத்தி தொடரவும்",
      quizBodyArea: "இது எங்கே அமைந்துள்ளது?",
      quizDuration: "இது எவ்வளவு காலமாக இருக்கிறது?",
      quizItchBurn: "அரிப்பு அல்லது எரிச்சல் இருக்கிறதா?",
      quizSpreading: "இது பரவுகிறதா?",
      quizAllergies: "ஏதேனும் ஒவ்வாமை உள்ளதா?",
      quizSkinTone: "உங்கள் தோல் நிறத்தைத் தேர்ந்தெடுக்கவும்",
      yes: "ஆம்",
      no: "இல்லை",
      days: "நாட்கள்",
      weeks: "வாரங்கள்",
      months: "மாதங்கள்",
      analyzing: "AI மூலம் பகுப்பாய்வு செய்யப்படுகிறது...",
      resultsTitle: "ஆரம்ப மதிப்பீடு",
      triageNow: "உடனடியாக மருத்துவரை அணுகவும்",
      triageWeek: "ஒரு வாரத்திற்குள் மருத்துவரை அணுகவும்",
      triageHome: "வீட்டிலேயே கண்காணிக்கவும்",
      findDoctor: "அருகிலுள்ள மருத்துவரைத் தேடுங்கள்",
      shareWhatsApp: "WhatsApp-ல் பகிரவும்",
      disclaimer: "மறுப்பு: இது ஒரு AI-இயங்கும் ஆதரவு கருவி, மருத்துவ நோயறிதல் அல்ல. எப்போதும் தகுதியான மருத்துவரை அணுகவும்.",
      cameraGuide: "பகுதியை வட்டத்திற்குள் வைத்திருங்கள். நல்ல வெளிச்சத்தை உறுதிப்படுத்தவும்.",
      lowLight: "குறைந்த வெளிச்சம் கண்டறியப்பட்டது. பிரகாசமான இடத்திற்குச் செல்லவும்.",
      blurDetected: "படம் மங்கலாக இருக்கலாம். நிலையாக இருங்கள்.",
      processing: "2G-க்காக சுருக்கப்படுகிறது...",
      historyEmpty: "இன்னும் ஸ்கேன்கள் இல்லை. உங்கள் முதல் ஸ்கேனைத் தொடங்குங்கள்!",
      deleteScan: "ஸ்கேனை நீக்கு",
      backToHome: "முகப்புக்குத் திரும்பு",
      voiceInput: "பேச தட்டவும் (இந்தி)",
    }
  },
  gu: {
    translation: {
      appName: "DermScan AI",
      tagline: "ભારત માટે AI-આધારિત ત્વચા સ્વાસ્થ્ય",
      startScan: "નવો સ્કેન શરૂ કરો",
      viewHistory: "સ્કેન ઇતિહાસ",
      step1Title: "ફોટો લો",
      step1Desc: "અસરગ્રસ્ત વિસ્તારનો સ્પષ્ટ ફોટો લો",
      step2Title: "લક્ષણ ક્વિઝ",
      step2Desc: "5 ઝડપી પ્રશ્નોના જવાબ આપો",
      step3Title: "AI મૂલ્યાંકન",
      step3Desc: "પ્રારંભિક પરિણામો મેળવો",
      captureButton: "ફોટો ખેંચો",
      retakeButton: "ફરીથી લો",
      confirmPhoto: "પુષ્ટિ કરો અને આગળ વધો",
      quizBodyArea: "તે ક્યાં આવેલું છે?",
      quizDuration: "તે કેટલા સમયથી છે?",
      quizItchBurn: "શું તેમાં ખંજવાળ કે બળતરા થાય છે?",
      quizSpreading: "શું તે ફેલાઈ રહ્યું છે?",
      quizAllergies: "કોઈ જાણીતી એલર્જી?",
      quizSkinTone: "તમારી ત્વચાનો રંગ પસંદ કરો",
      yes: "હા",
      no: "ના",
      days: "દિવસો",
      weeks: "અઠવાડિયા",
      months: "મહિના",
      analyzing: "AI સાથે વિશ્લેષણ થઈ રહ્યું છે...",
      resultsTitle: "પ્રારંભિક મૂલ્યાંકન",
      triageNow: "તરત જ ડોક્ટરને મળો",
      triageWeek: "એક અઠવાડિયામાં ડોક્ટરને બતાવો",
      triageHome: "ઘરે દેખરેખ રાખો",
      findDoctor: "નજીકના ડોક્ટર શોધો",
      shareWhatsApp: "WhatsApp પર શેર કરો",
      disclaimer: "ડિસ્ક્લેમર: આ એક AI-આધારિત સહાયક સાધન છે, તબીબી નિદાન નથી. હંમેશા લાયક ડોક્ટરની સલાહ લો.",
      cameraGuide: "વિસ્તારને વર્તુળની અંદર રાખો. સારી લાઇટિંગની ખાતરી કરો.",
      lowLight: "ઓછી લાઇટ મળી. કૃપા કરીને તેજસ્વી વિસ્તારમાં જાઓ.",
      blurDetected: "ફોટો ઝાંખો હોઈ શકે છે. કૃપા કરીને સ્થિર રહો.",
      processing: "2G માટે કોમ્પ્રેસ થઈ રહ્યું છે...",
      historyEmpty: "હજી સુધી કોઈ સ્કેન નથી. તમારો પહેલો સ્કેન શરૂ કરો!",
      deleteScan: "સ્કેન દૂર કરો",
      backToHome: "હોમ પર પાછા જાઓ",
      voiceInput: "બોલવા માટે ટેપ કરો (હિન્દી)",
    }
  },
  mr: {
    translation: {
      appName: "DermScan AI",
      tagline: "भारतासाठी AI-आधारित त्वचा आरोग्य",
      startScan: "नवीन स्कॅन सुरू करा",
      viewHistory: "स्कॅन इतिहास",
      step1Title: "फोटो घ्या",
      step1Desc: "प्रभावित भागाचा स्पष्ट फोटो घ्या",
      step2Title: "लक्षण प्रश्नमंजुषा",
      step2Desc: "5 त्वरित प्रश्नांची उत्तरे द्या",
      step3Title: "AI मूल्यांकन",
      step3Desc: "प्रारंभिक निकाल मिळवा",
      captureButton: "फोटो काढा",
      retakeButton: "पुन्हा घ्या",
      confirmPhoto: "पुष्टी करा आणि पुढे जा",
      quizBodyArea: "ते कोठे आहे?",
      quizDuration: "ते किती दिवसांपासून आहे?",
      quizItchBurn: "खाज सुटते किंवा जळजळ होते का?",
      quizSpreading: "ते पसरत आहे का?",
      quizAllergies: "काही ज्ञात ॲलर्जी?",
      quizSkinTone: "तुमच्या त्वचेचा रंग निवडा",
      yes: "हो",
      no: "नाही",
      days: "दिवस",
      weeks: "आठवडे",
      months: "महिने",
      analyzing: "AI सह विश्लेषण होत आहे...",
      resultsTitle: "प्रारंभिक मूल्यांकन",
      triageNow: "त्वरीत डॉक्टरांना भेटा",
      triageWeek: "एका आठवड्यात डॉक्टरांना दाखवा",
      triageHome: "घरी लक्ष ठेवा",
      findDoctor: "जवळचे डॉक्टर शोधा",
      shareWhatsApp: "WhatsApp वर शेअर करा",
      disclaimer: "अस्वीकरण: हे एक AI-आधारित सहाय्यक साधन आहे, वैद्यकीय निदान नाही. नेहमी पात्र डॉक्टरांचा सल्ला घ्या.",
      cameraGuide: "भाग वर्तुळाच्या आत ठेवा. चांगली प्रकाश व्यवस्था सुनिश्चित करा.",
      lowLight: "कमी प्रकाश आढळला. कृपया उजेड असलेल्या ठिकाणी जा.",
      blurDetected: "फोटो पुसट असू शकतो. कृपया स्थिर रहा.",
      processing: "2G साठी कॉम्प्रेस होत आहे...",
      historyEmpty: "अद्याप कोणतेही स्कॅन नाहीत. तुमचा पहिला स्कॅन सुरू करा!",
      deleteScan: "स्कॅन हटवा",
      backToHome: "होमवर परत जा",
      voiceInput: "बोलण्यासाठी टॅप करा (हिंदी)",
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: 'hi',
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
